### ISSUE TITLE
Open on Click doesn't works

### ISSUE THREAD

**Issue by Laul0** [devlabnet/SlideShow#21] opened 2016-01-06 16:58 UTC
Hi,

I use the latest version of SliderShow from GitHub and I use it with CKEditor 4.5.
I can add a SlideShow, manage images, effect, etc. without any problem... But I can't use "Open On Click" because it doesn't work :/
I checked JavaScript console > No error
And everything else works.

Have you any idea?

Thx

**Comment by cricri042** [comment] 2016-01-06 18:40
Hi Laul0,
Quite strange !!. Anyway I did some fixes a minute ago, can you try with the latest version ?
By the way, when you say "I can't use 'open on click'", you mean that doesn't work on the generated page (nothing happen when you click on the image) ?.
If yes, does it work in the preview panel (I mean does a fancybox open if you click on the image in the preview panel, with the "open on click" checked) ?

--Christian

**Comment by Laul0** [comment] 2016-01-06 19:45
Hi,

Thank you for you quick answer!
I'll try the latest version as soon as possible.
Yes, is exactly what I mean.
In the preview it doesn't works neither :/

> open on click is checked when I save

Thx

**Comment by Laul0** [comment] 2016-01-06 21:56
I downloaded your latest version.
1- Open on click works with the default picture in the preview and once the code was generated
2- If I add a new picture, "Open On click" works with the default picture but it doesn't work with my picture.

When I say "it doesn't work" it's when you said : "nothing happen when I click on the image"

Example of URL of picture : /my-site/handler/s/my-image (relative URL)
Is it because I use a handler and the file have no extension?
Is it because I use a handler?

Any other idea?

Thx

**Comment by cricri042** [comment] 2016-01-07 10:35
Hi,
Yep, I suspect that the problem is coming from the way your handling the images.
I just created a branch on GitHub : Laul0, this is noting really new in this branch, except I added a console print to display the path of the image file who will normally displayed in the fancy Box.
Can you try this branch, and look in the console when you click on the image, normally you will get something like that:
...
isrc: /slideshow/filemanager/userfiles/5740183157_baaa10cfa6.jpg
...

Just to check if the path to the clicked image is ok or not !!

  --Christian

**Comment by Laul0** [comment] 2016-01-07 11:02
Hi,

I downloaded your sources form the Laul0 branch.
Here, the result of the console when I click on an image :
- image 1 = isrc: /handler/s/star-wars-black-star
- image 2 = isrc: /handler/s/intro-claire-vernoux-3950

Find enclose the sources generated by your plugin.
[SlideShow_Source_Laul0.rtf.zip](https://github.com/devlabnet/SlideShow/files/81019/SlideShow_Source_Laul0.rtf.zip)

**Comment by cricri042** [comment] 2016-01-07 12:43
Hi,
Ok, so what is exactly behind the: “/handler/s/star-wars-black-star”?.
The problem is because the href file as no image extention.
I checked what is done in the fancybox script and they use a function : 
isImage: function (str) {
return isString(str) && str.match(/(^data:image\/.*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg)((\?|#).*)?$)/i);
}

Who check the type of object. So as the type is not recognized as something valid, open is not done. Is it a way to be able to have the file extention at this point ?

  --Christian

**Comment by cricri042** [comment] 2016-01-07 13:02
Hi Laul0,
I just did a try for a "hack" fix for you, can you try with the new version in your branch ?
I just added that in case of no detected type, the type is forced to an image !!

  --Christian

**Comment by Laul0** [comment] 2016-01-07 14:30
Hi Christian,

I tried the last version from Laul0 branch and it's works :)
Good Job! Thank you very much
I think this "bug" is very important because in my case I use a handler and maybe other users can use image with a src in base64. What do you think?

And I have an over suggestion for you, to improve your plugin if you want :)
When you "open image on click", I think this is a great idea to add arrows to switch with the next or previous image... As that, you must don't close the fancyBox and you can see the next/previous image directly (an new option)

**Comment by cricri042** [comment] 2016-01-08 11:53
Fix merged to master

**Closed by cricri042** 2016-01-08 11:53 UTC
